import type { DraftView } from "./types";

/** A draft as the API returns it right after an upload: fictional leads.csv, three rows. Tests only. */
export function testDraft(over: Partial<DraftView> = {}): DraftView {
  return {
    id: "0190e0c0-0000-7000-8000-00000000d001",
    status: "draft",
    fileName: "leads.csv",
    fileBytes: 96,
    encoding: "utf-8",
    delimiter: ",",
    headerRow: 1,
    headers: ["Full name", "Mobile", "Email"],
    sample: [
      ["Aisha Khan", "050 123 4567", "aisha@example.test"],
      ["Omar Farouk", "+971 55 234 5678", ""],
      ["Priya Menon", "", "priya@example.test"],
    ],
    rowCount: 3,
    fileWarnings: [],
    mapping: {
      columns: [
        { column: 0, to: "field", field: "name" },
        { column: 1, to: "field", field: "phone" },
        { column: 2, to: "field", field: "email" },
      ],
      createMissingTags: false,
    },
    rules: {
      matchOn: ["phone", "email", "instagram"],
      onMatch: "merge",
      reopenClosedTo: null,
      pipelineId: "p1",
      stageId: "s-new",
      owner: { mode: "unassigned" },
      defaultCountry: "AE",
      noName: "use_contact",
      unknownOwner: "fallback",
      requiredDefaults: {},
    },
    targets: [
      { key: "name", label: "Name", group: "Lead" },
      { key: "phone", label: "Phone", group: "Contact" },
      { key: "email", label: "Email", group: "Contact" },
      { key: "instagram", label: "Instagram", group: "Contact" },
      { key: "owner", label: "Handled by (owner)", group: "Lead" },
      { key: "stage", label: "Stage", group: "Lead" },
      { key: "value", label: "Value", group: "Lead" },
      { key: "lead_created_at", label: "Date", group: "Lead" },
      { key: "struggles", label: "Struggles", group: "Custom" },
      { key: "tags", label: "Tags", group: "Lead" },
      { key: "lost_reason", label: "Lost reason", group: "Lead" },
    ],
    analysis: [
      { column: 0, unmatched: [] },
      { column: 1, unmatched: [] },
      { column: 2, unmatched: [] },
    ],
    problems: [],
    alreadyImported: null,
    choices: {
      pipelines: [{ id: "p1", name: "Coaching sales", isDefault: true }],
      stages: [
        { id: "s-new", name: "New", kind: "open" },
        { id: "s-sent", name: "Message sent", kind: "open" },
        { id: "s-booked", name: "Call booked", kind: "open" },
        { id: "s-won", name: "Won", kind: "won" },
        { id: "s-lost", name: "Lost", kind: "lost" },
      ],
      people: [
        { id: "u-riya", name: "Riya Sharma", email: "riya@brightpath.test" },
        { id: "u-tas", name: "Leila Haddad", email: "leila@brightpath.test" },
      ],
      fields: [
        {
          id: "f-name",
          key: "name",
          label: "Name",
          type: "text",
          options: [],
          isCore: true,
          isRequired: true,
          archived: false,
          access: "edit",
        },
        {
          id: "f-phone",
          key: "phone",
          label: "Phone",
          type: "phone",
          options: [],
          isCore: true,
          isRequired: false,
          archived: false,
          access: "edit",
        },
        {
          id: "f-email",
          key: "email",
          label: "Email",
          type: "email",
          options: [],
          isCore: true,
          isRequired: false,
          archived: false,
          access: "edit",
        },
        {
          id: "f-struggles",
          key: "struggles",
          label: "Struggles",
          type: "multi_select",
          options: [
            { id: "o-conf", label: "Confidence" },
            { id: "o-career", label: "Career switch" },
          ],
          isCore: false,
          isRequired: false,
          archived: false,
          access: "edit",
        },
      ],
    },
    can: { assign: true, manageFields: true, manageTags: true },
    ...over,
  };
}
