- navigation "Settings":
    - link "All settings":
        - /url: /settings
    - group "You":
        - link "Calendar":
            - /url: /settings/calendar
        - link "My account":
            - /url: /settings/account
        - link "About":
            - /url: /settings/about
